# Problema 1

Las matrices $A$ y $B$ representan las ventas en dos años, en millones de dólares, de los tres productos de una empresa en las cuatro regiones en que está disponible. Es decir, $a_{ij}$ y $b_{ij}$ representan el monto de las ventas del producto $i$ en la región $j$ el primer y segundo año, respectivamente:

<br>

\begin{split}
A = \begin{pmatrix}
 2,6 &  4,8 &  1,8 & 0,9 \\
 3,2 &  4,4 &  2,5 & 2,8 \\
 2,4 &  3,6 &  3,8 & 2,5 \\
\end{pmatrix} \text{ } B= \begin{pmatrix}
 3,6 &  2,5 &  3,0 & 2,5 \\
 4,5 &  5,0 &  3,5 & 3,8 \\
 2,9 &  3,0 &  4,6 & 4,0 \\
\end{pmatrix}
\end{split}

<br>

1. Indique el orden de cada matriz.
2. Calcule la matriz $S = A + B$.
3. Calcule la matriz $D = B - A$.
4. Indique el valor e interprete los elementos $s_{24}$ y $d_{24}$.
5. Para el tercer año de funcionamiento, los tres productos ahora están disponibles en seis regiones. Durante este año, las ventas de esta empresa estarán registradas en una matriz $E$. ¿Es posible determinar la matriz $T = A + B + E$? Justifique su respuesta.

In [21]:
#Matrices 3 4
#Tiene tres productos --> filas = productos
#Me dice que hay cuatro regiones --> columnas = regiones

# A = ventas del primer año de 3 productos en 4 regiones
# B = ventas del segundo año de 3 productos en 4 regiones

#1 
print("1. \nOrden: 3 x 4")

#2 - Suma de las matrices

import numpy as np

#Declarar matrices según numpy
A = np.array([[2.6, 4.8, 1.8, 0.9], [3.2, 4.4, 2.5, 2.8], [2.4, 2.6, 3.8, 2.5]])
B = np.array([[3.6, 2.5, 3.0, 2.5], [4.5, 5.0, 3.5, 3.8], [2.9, 3.0, 4.6, 4.0]])

S = A + B
print(f"\n2. \n{S}")

#3 - D = B - A

D = B - A
print(f"\n3. D = B - A \n{D}")

#4. Indique el valor e interprete los elementos s24 y d24.

#s24
# Matriz suma (S) --> representa el total de ventas de los 2 años
# Fila 2 = representa el segundo producto
# Columna 4 = representa la cuarta región

s24 = S[2-1][4-1]

print("\n 4.")
print(f"Después de 2 años se vendieron {s24} millones de dólares por las ventas del producto 2 en la cuarta región.")

d24 = D[2-1][4-1]

print(f"La diferencia entre las ventas del 2do y 1er años, del producto 2 en la región 4 fue de {d24} millones de dólares.")

#5. 
print("5. \nNo es posible determinar la raiz T ya que la matriz A y matriz B son 3x4, pero en cambio la matriz E es 3x6. Por lo tanto no se pueden sumar porque no tienen el mismo orden.")


1. 
Orden: 3 x 4

2. 
[[6.2 7.3 4.8 3.4]
 [7.7 9.4 6.  6.6]
 [5.3 5.6 8.4 6.5]]

3. D = B - A 
[[ 1.  -2.3  1.2  1.6]
 [ 1.3  0.6  1.   1. ]
 [ 0.5  0.4  0.8  1.5]]

 4.
Después de 2 años se vendieron 6.6 millones de dólares por las ventas del producto 2 en la cuarta región.
La diferencia entre las ventas del 2do y 1er años, del producto 2 en la región 4 fue de 1.0 millones de dólares.
5. 
No es posible determinar la raiz T ya que la matriz A y matriz B son 3x4, pero en cambio la matriz E es 3x6. Por lo tanto no se pueden sumar porque no tienen el mismo orden.


# Problema 2

Una fábrica con sucursales en Japón y China, produce tres tipos de componentes $j$, para cinco modelos de computador $i$. Los costos de producción mensual, en miles de dólares, de ambas sucursales se representan en las matrices $J$ y $C$, respectivamente:

<br>

\begin{split}
J = \begin{pmatrix}
 100 &  200 &  150  \\
 120 &  210 &  170  \\
 112 &  200 &  131  \\
 124 &  310 &  170  \\
 136 &  156 &  140  \\
\end{pmatrix} \text{ } C = \begin{pmatrix}
 110 &  190 &  160  \\
 130 &  220 &  180  \\
 146 &  190 &  141  \\
 143 &  312 &  163  \\
 137 &  116 &  156  \\
\end{pmatrix}
\end{split}

<br>

1. ¿Cuál es el orden de las matrices?
2. Inteprete el elemento $j_{21}$ y $c_{12}$ en el contexto del problema.
3. Utilizando *Python*, calcule el costo total de producción para cada modelo, considerando ambas sucursales.
4. Un trabajador indica que, en la sucursal japonesa, el costo de producción del producto $3$, modelo $4$ de computador, es más alto que en la sucursal china. ¿Tiene razón? Justifique apropiadamente.

In [ ]:
# j = componentes --> columnas
# i = modelos de computador --> filas

#1
print("1. El orden de las matrices es de 5x3")

#2
import numpy as np

J = np.array([[100, 200, 150], [120, 210, 170], [112, 200, 131], [124, 310, 170], [136, 156, 140]])
C = np.array([[110, 190, 160], [130, 220, 180], [146, 190, 141], [143, 312, 163], [137, 116, 156]])

print(f" J = \n{J}")
print(f" C = \n{C}")

# j21:
#fila 2 --> segundo componente
# columna 1 --> 1er modelo

print("\n2. ")

j21 = J[2-1][1-1]
print(f"j21 = Mensualmente en la sucursal de Japón, el segundo componente junto con el primer modelo cuestan {j21} miles de dólares")

c12 = C[1-1][2-1]
print(f"c12 = Mensualmente en la sucursal de China, el primer componente junto con el segundo modelo cuestan {c12} miles de dólares")


#3. Calcular el costo total de producción para cada modelo (cada modelo tiene 3 componentes) --> sumar cada modelo (fila) con sus 3 componentes

#Costo total de producción para cada modelo en Japón

# a) Creo una lista vacía que va a contener la suma de las filas
total_modelo_J = []

# Voy a convertir la matriz en una lista para que no me printee "[np.int64(450), np.int64(500), np.int64(443), np.int64(604), np.int64(432)]"
J_list = J.tolist()


# b) Hago un "for" para cada fila (cada fila está dentro de una lista) en la matriz
# c) Luego sumaré los valores de cada lista en la matriz (que contienen las filas) y cada suma la agregaré a la lista creada.

for modelo in J_list:
    total_modelo_J.append(sum(modelo))

print(total_modelo_J)


total_modelo_J = np.sum(J, axis=1)
print(total_modelo_J)

#Costo total de producción para cada modelo en China


#Para que la matriz sea vea en vértical

#1era forma profe

sumaC = []
for i in range(len(C)):
    sumaC.append(sum(C[i]))

#Acá me saldrán los resultados con np.int64

#Como quitar eso:
sumaC = np.array(sumaC)

#Para que sea vea en vértical (así sé que son filas)

# 2da forma profe
#Sumar las filas con numpy
sumaC = np.sum(C, axis=1)

print(sumaC)


#Calcular el costo total de producción para cada modelo (sumar las filas)

#Japón
total_modelo_J = np.sum(J, axis=1)
print(f"El total de producción para cada modelo en Japón es: {total_modelo_J}")

#China
total_modelo_C = np.sum(C, axis=1)
print(f"El total de producción para cada modelo en China es: {total_modelo_C}")

#axis 0 -->  para sumar columnas
#axis 1 --> sumar filas


#Un trabajador indica que, en la sucursal japonesa, el costo de producción del componente 3, modelo 4 de computador, 
# es más alto que en la sucursal china. ¿Tiene razón? Justifique apropiadamente.

print(f"4. En Japón sería 170 y en China 163, por lo tanto el trabajador tiene razón.")





1. El orden de las matrices es de 5x3
 J = 
[[100 200 150]
 [120 210 170]
 [112 200 131]
 [124 310 170]
 [136 156 140]]
 C = 
[[110 190 160]
 [130 220 180]
 [146 190 141]
 [143 312 163]
 [137 116 156]]

2. 
j21 = Mensualmente en la sucursal de Japón, el segundo componente junto con el primer modelo cuestan 120 miles de dólares
c12 = Mensualmente en la sucursal de China, el primer componente junto con el segundo modelo cuestan 190 miles de dólares
[450, 500, 443, 604, 432]
[450 500 443 604 432]
[460 530 477 618 409]
El total de producción para cada modelo en Japón es: [450 500 443 604 432]
El total de producción para cada modelo en China es: [460 530 477 618 409]


# Problema 3

La empresa Beta tiene cinco plantas en Chile, y en cada una de ellas fabrica siete productos. El número de unidades del producto $i$ fabricadas en la planta $j$ en una semana está representado en la matriz $C$ en el elemento $c_{ij}$.

<br>

\begin{split}
C = \begin{pmatrix}
 120 &  200 &  155 &  125  &  230 \\
 155 &  130 &  110 &  160  &  180 \\
 140 &  205 &  150 &  125  &  155 \\
 130 &  120 &  230 &  225  &  125 \\
 135 &  70  &  190 &  175  &  95  \\
 110 &  265 &  180 &  230  &  180 \\
 185 &  85  &  120 &  135  &  150 \\
\end{pmatrix}
\end{split}

<br>

La empresa se expande, creando cinco plantas en Ecuador que producen los mismos siete productos. La producción semanal de esta filial estará representada por una matriz $E$.

1. Si se sabe que los volúmenes de producción semanal de la filial en Ecuador son un $20\%$ menor que en Chile, calcule la matriz $E$ utilizando *Python*.
2. Si representamos la producción semanal total de la empresa Beta, considerando ambas filiales, por la matriz $T$, escriba la expresión que calcula cada elemento de la matriz $T$ usando notación matricial.
3. Calcule la matriz $T$ utilizando *Python*.
4. Interprete los elementos $c_{34}$ y $t_{72}$ en el contexto del problema.

In [ ]:
# fila --> producto
# columnas --> plantas

import numpy as np

C = np.array([[120, 200, 155, 125, 230],[155, 130, 110, 160, 180],[140, 205, 150, 125, 155],[130, 120, 230, 225, 125], [135, 70, 190, 175, 95], [110, 265, 180, 230, 180],[185,85, 120, 135, 150]])


#1
#Ecuador = 20% menor que en Chile = 100% - 20% = 80% --> 0.8
E = 0.8*C

#2 - Total = Chile + Ecuador
T = C + E
# T = C + E
# T --> Tij
# C --> Cij
# E --> Eij

# tij = cij + eij

#3 
print(f"La producción total es: {T}")

#4 interpretar c34 y t72

c34 = C[3-1][4-1]
t72 = T[7-1][2-1]

print(f"En la planta de Chile se fabrican {c34} unidades del producto 3 en la planta 4, a la semana")
print(f"En total, se fabrican {t72} unidades del producto 7 en la planta 2, a la semana (entre ambas plantas)")


La producción total es: [[216. 360. 279. 225. 414.]
 [279. 234. 198. 288. 324.]
 [252. 369. 270. 225. 279.]
 [234. 216. 414. 405. 225.]
 [243. 126. 342. 315. 171.]
 [198. 477. 324. 414. 324.]
 [333. 153. 216. 243. 270.]]
En la planta de Chile se fabrican 125 unidades del producto 3 en la planta 4, a la semana
En total, se fabrican 153.0 unidades del producto 7 en la planta 2, a la semana (entre ambas plantas)


# Problema 4

Una empresa que fabrica zapatos tiene dos plantas, una en Valparaíso y la otra en Temuco. La empresa produce zapatos de color negro, blanco y café, tanto para niños, damas como caballeros. La capacidad actual de producción mensual (en miles de pares) para Valparaíso y Temuco, están dadas por las matrices $V$ y $T$, respectivamente. Para ambas matrices, según el orden en que se mencionan, las filas corresponden al color del calzado y las columnas al tipo de persona que utilizará el calzado.

<br>

\begin{split}
V = \begin{pmatrix}
 30 &  34 &  20  \\
 45 &  20 &  16  \\
 14 &  26 &  25  \\
\end{pmatrix} \text{ } T = \begin{pmatrix}
 35 &  30 &  26  \\
 52 &  25 &  18  \\
 23 &  24 &  32  \\
\end{pmatrix}
\end{split}

<br>

1. Determine la producción mensual total de ambas plantas, representándola en una matriz $A$. Utilice *Python* para resolver.
2. Interprete el elemento $a_{21}$ en el contexto del problema.
3. Si para el próximo año se estima que la producción en Valparaíso aumenta en un $30\%$, mientras que la de Temuco se reduce en un $10\%$, represente la nueva producción total en la matriz $B$.
4. Interprete el elemento $b_{13}$ en el contexto del problema.

In [25]:
# Capacidad actual de producción mensual (en miles de pares)
#filas --> color calzado
#columnas --> tipo de persona que utilizará el calzado

import numpy as np

V = np.array([[30, 34, 20], [45, 20, 16], [14, 26, 25]])
T = np.array([[35, 30, 26], [52, 25, 18], [23, 24, 32]])

#1
A = V + T

print(f"La producción mensual de ambas plantas es {A}")

#2. Interprete a21
a21 = A[2-1][1-1]
print(f"La producción mensual de ambas plantas del zapato de color blanco para niños es de {a21} miles de pares. ")

#3
V1 = 1.30 * V
T1 = 0.9* T

B = V1 + T1
print(f"3. La nueva producción total de la matriz B es: \n{B}")


#4. Interpreta b13
b13 = B[1-1][3-1]
print(f"La producción mensual de ambas plantas para el próximo del zapato de color negro para caballeros será de {round(b13,1)} miles de pares.")


La producción mensual de ambas plantas es [[65 64 46]
 [97 45 34]
 [37 50 57]]
La producción mensual de ambas plantas del zapato de color blanco para niños es de 97 miles de pares. 
3. La nueva producción total de la matriz B es: 
[[ 70.5  71.2  49.4]
 [105.3  48.5  37. ]
 [ 38.9  55.4  61.3]]
La producción mensual de ambas plantas para el próximo del zapato de color negro para caballeros será de 49.4 miles de pares.


# Problema 5

Genere una matriz $M$ de orden $8 \times 9$ donde cada término de la matriz está definido por:

$$m_{ij} = 8i + 12j$$

y calcule su transpuesta.

In [ ]:
# mmij = 8i + 12j (en matriz 2x2)
# (m11 m12) = (8*1 + 12*1)= 28  ( 8*1 + 12*2) = 32)
# (m21 m22) = (8*2 + 12*1)= 28  (8*2 + 12*2) =  40)

import numpy as np

#Python comienza desde 0 y se sumará 1 a las variables
EJ = np.fromfunction(lambda i,j: 8*(i+1) + 12*(j+1), (2,2))
print(f"Ejemplo de arriba \n{EJ}\n")

M = np.fromfunction(lambda i,j: 8*(i+1) + 12*(j+1), (8,9))
print(M)

#Calcule su transpuesta
#Transpuesta = matriz al revés (solo se le agrega ".T")
# Ej al tener una matriz 3x2, transpuesta será 2x3

M = M.T
print(M)

Ejemplo de arriba 
[[20. 32.]
 [28. 40.]]

[[ 20.  32.  44.  56.  68.  80.  92. 104. 116.]
 [ 28.  40.  52.  64.  76.  88. 100. 112. 124.]
 [ 36.  48.  60.  72.  84.  96. 108. 120. 132.]
 [ 44.  56.  68.  80.  92. 104. 116. 128. 140.]
 [ 52.  64.  76.  88. 100. 112. 124. 136. 148.]
 [ 60.  72.  84.  96. 108. 120. 132. 144. 156.]
 [ 68.  80.  92. 104. 116. 128. 140. 152. 164.]
 [ 76.  88. 100. 112. 124. 136. 148. 160. 172.]]
[[ 20.  28.  36.  44.  52.  60.  68.  76.]
 [ 32.  40.  48.  56.  64.  72.  80.  88.]
 [ 44.  52.  60.  68.  76.  84.  92. 100.]
 [ 56.  64.  72.  80.  88.  96. 104. 112.]
 [ 68.  76.  84.  92. 100. 108. 116. 124.]
 [ 80.  88.  96. 104. 112. 120. 128. 136.]
 [ 92. 100. 108. 116. 124. 132. 140. 148.]
 [104. 112. 120. 128. 136. 144. 152. 160.]
 [116. 124. 132. 140. 148. 156. 164. 172.]]


# Problema 6

Genere dos matrices:

*   Una matriz $A$ de orden $5 \times 7$, con $a_{ij} = i \cdot j.$
*   Una matriz $B$ de orden $7 \times 5$, con $b_{ij} = 15i - 2j.$

y calcule $C = A^{T} + \dfrac{1}{2}B$.



In [41]:
import numpy as np
A = np.fromfunction(lambda i,j: (i+1)*(j+1), (5,7))
B = np.fromfunction(lambda i,j: 15*(i+1)-2*(j+1), (7,5))

print(A)
print(B)

#C

C = A.T + 1/2*B

print(f"\nC:\n{C}")


[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]
[[ 13.  11.   9.   7.   5.]
 [ 28.  26.  24.  22.  20.]
 [ 43.  41.  39.  37.  35.]
 [ 58.  56.  54.  52.  50.]
 [ 73.  71.  69.  67.  65.]
 [ 88.  86.  84.  82.  80.]
 [103. 101.  99.  97.  95.]]

C:
[[ 7.5  7.5  7.5  7.5  7.5]
 [16.  17.  18.  19.  20. ]
 [24.5 26.5 28.5 30.5 32.5]
 [33.  36.  39.  42.  45. ]
 [41.5 45.5 49.5 53.5 57.5]
 [50.  55.  60.  65.  70. ]
 [58.5 64.5 70.5 76.5 82.5]]


# Problema 7

Una red de sensores recoge datos de temperatura ($°C$), humedad (porcentaje) y presión (hPa) en cinco días distintos (de lunes a viernes). Los datos medidos se muestran en la matriz $D$:

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & Lu  \ \ &Ma \ \ &Mi \ \ & Ju \ \ &Vi
\end{matrix} \\
&D = \begin{pmatrix}
20    &  28    &  22    &  26     &  24   \\
52    &  57    &  56    &  54     &  58   \\
1.066 &  1.068 &  1.066 &  1.064  &  1.068 \\
\end{pmatrix} & \ \begin{matrix}
Cº\\
\% \\
hPa
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

Se sabe que por un error de calibración de los sensores, las medidas registradas deberían ser un $5\%$ menores que las registradas.

1. Calcule en una matriz $S$ los valores correctos de temperatura, humedad y presión. Utilice *Python* para calcular.
2. Obtenga la matriz $S^{T}$.
3. Interprete los elementos $s_{24}$ y $s_{31}^{T}$.


In [50]:
D = np.array([[20, 28, 22, 26, 24], [52, 57, 56, 54, 58], [1066, 1068, 1066, 1064, 1068]])
S = D * 0.95
print(f"1. \n{S}\n")

#2
print(f"2. La matriz S transpuesta es: \n{S.T}\n")

#3. Interpreta s24 y ST31

s24 = S[2-1][4-1]
st31 = S.T[3-1][1-1]

print(f"3. \ns24: El día jueves hay húmedad de {s24}%")
print(f"st31: El día miércoles hay una temperatura de {st31}°C.")




1. 
[[  19.     26.6    20.9    24.7    22.8 ]
 [  49.4    54.15   53.2    51.3    55.1 ]
 [1012.7  1014.6  1012.7  1010.8  1014.6 ]]

2. La matriz S transpuesta es: 
[[  19.     49.4  1012.7 ]
 [  26.6    54.15 1014.6 ]
 [  20.9    53.2  1012.7 ]
 [  24.7    51.3  1010.8 ]
 [  22.8    55.1  1014.6 ]]

3. 
s24: El día jueves hay húmedad de 51.3%
st31: El día miércoles hay una temperatura de 20.9°C.


# Problema 8

Una empresa tecnológica vende software y hardware en tres productos: $P_{1}$, $P_{2}$ y $P_{3}$, en cuatro zonas de la capital: norte, sur, este y oeste. Las ventas del mes, en millones de pesos, están registradas en las matrices $S$ y $H$, para software y hardware respectivamente.

<br>

\begin{split}
S = \begin{pmatrix}
 260 &  480 &  180  &  90  \\
 320 &  440 &  250  &  280 \\
 240 &  360 &  380  &  250  \\
\end{pmatrix} \text{ } H = \begin{pmatrix}
 360 &  250 &  300  &  250  \\
 450 &  500 &  350  &  380 \\
 290 &  300 &  460  &  400  \\
\end{pmatrix}
\end{split}

<br>

1. Calcule en la matriz $T$, del total de ventas de la empresa tecnológica.
2. Un trabajador indica que este mes, la sucursal de la zona sur recaudó más por la venta hardware que software, ¿es correcta su afirmación?
3. Debido al black friday se espera que el siguiente mes, las ventas de software aumenten un $7\%$ y las de hardware aumenten un $3\%$ respecto al mes actual. Encuentra en total de ventas esperadas para el siguiente mes y almacénalo en la matriz $M$. Utiliza *Python* para realizar los cálculos.
4. Interpreta los elementos $t_{24}$ y $m_{31}$ en el contexto del problema.
5. Calcula la matriz $M^{T}$ e interpreta el elemento $m_{41}^{T}$ en el contexto del problema.


In [ ]:
import numpy as np

S = np.array([[260, 480, 180, 90], [320, 440, 250, 280], [240, 360, 380, 250]])
H = np.array([[360, 250, 300, 250], [450, 500, 350, 380], [290, 300, 460, 400]])

#1
T = S + H
print(f"1.El total de ventas de la empresa tecnológica es: \n{T}")

#2. Debo sumar los productos de la zona sur --> sumar filas
#axis 0 -->  para sumar columnas
#axis 1 --> sumar filas

#Suma de los productos Software por zona 
S_zona = np.sum(S, axis=0)
print(f"Suma de los productos software por zona: {S_zona}")

#Suma de los productos Hardware por zona
H_zona = np.sum(H, axis=0)
print(f"Suma de los productos hardware por zona: {H_zona}")

print("Las ventas por software de la zona sur fueron de 1280, y de hardware fueron de 1050. Por lo tanto la afirmación es falsa, se recaudó más por software.")





1.El total de ventas de la empresa tecnológica es: 
[[620 730 480 340]
 [770 940 600 660]
 [530 660 840 650]]
Suma de los productos software por zona: [ 820 1280  810  620]
Suma de los productos hardware por zona: [1100 1050 1110 1030]
