# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [3]:
import numpy as np

A = np.array([[1,2],[3,2]])
B = np.array([[290,312],[345,413]])

#1
#El orden de A es 2x2
#El orden de B es 2x2
#El orden de la matiz C es 2x2 (filas de primera matriz por columnas de segunda matriz)

print("Si es factible multiplicar, ya que la cantidad de columnas de la primera matriz es igual a la cantidad de filas de la segunda matriz.")

C = A@B
print(f"2.\n{C}")

c21 = C[2-1][1-1]
print("c21 = ")
c11 = C[1-1][1-1]

print(f"El elemento c21 es {c21}. Se utilizaron {c21} kg de aluminio en el mes de enero para la fabricación de ambos modelos.")
print(f"El elemento c11 es {c11}. Se utilizaron {c11} kg de aluminio en el mes de enero para la fabricación de ambos modelos.")

Si es factible multiplicar, ya que la cantidad de columnas de la primera matriz es igual a la cantidad de filas de la segunda matriz.
2.
[[ 980 1138]
 [1560 1762]]
c21 = 
El elemento c21 es 1560. Se utilizaron 1560 kg de aluminio en el mes de enero para la fabricación de ambos modelos.
El elemento c11 es 980. Se utilizaron 980 kg de aluminio en el mes de enero para la fabricación de ambos modelos.


# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [10]:
#1
print("1. El orden de la Matriz P es 1x3 y el orden de la matriz V es 3x3")

#2
import numpy as np

P = np.array([[4200, 1500, 3200]])
V = np.array([[1300, 900, 800],[2100,1700,1500],[1500,1200,900]])

I = P@V
print(I)

v32 = V[3-1][2-1]
p12 = P[1-1][2-1]
i13 = I[1-1][3-1]

#3
print(f"v32: En la sucural de Concepción hay {v32} unidades de mateadas.")
print(f"p12: En la sucural de Concepción el precio de las hamburguesas es de ${p12} por unidad.")
print(f"i13: En la sucural de Antofagaste, el precio total recaudado de los tres productos durante el fin de semana fue de ${i13}")



1. El orden de la Matriz P es 1x3 y el orden de la matriz V es 3x3
[[13410000 10170000  8490000]]
v32: En la sucural de Concepción hay 1200 unidades de mateadas.
p12: En la sucural de Concepción el precio de las hamburguesas es de $1500 por unidad.
i13: En la sucural de Antofagaste, el precio total recaudado de los tres productos durante el fin de semana fue de $8490000


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [ ]:
#1
print(f"1.El orden de la matriz M es 2x2 y el orden de la matriz Q es 2x3.")
# 2x2 = transitores/receptores x modelos
# 2x3 = cantidades cada modelo x semanas

#2
print("2.\nLa matriz G si se puede calcular ya que las filas de la primera matriz es del mismo orden que las columnas de la segunda matriz.")
print("La matriz H no se puede calcular, ya que las filas de la primera matriz con las columnas de la segunda no son del mismo orden.")

#3
import numpy as np

M = np.array([[9,14],[4,5]])
Q = np.array([[200, 240, 220],[175, 210, 215]])

G = M@Q

print(G)

g23 = G[2-1][3-1]
g12 = G[1-1][2-1]

print(f"\n3.\ng23: Se produjeron un total de {g23} resistores en la 3era semana")
print(f"g12: Se produjeron un total de {g12} transitores en la 2da semana")


#4
print(f"\n4.\nSe utilizaron un total de {1675+2010+1955} resistores durante las 3 semanas.")

#Segunda forma
resistores_3_semanas = np.sum(G[1,:])
#Sumar la fila 2 (posición 1), con todas las columnas.
print(resistores_3_semanas)



1.El orden de la matriz M es 2x2 y el orden de la matriz Q es 2x3.
2.
La matriz G si se puede calcular ya que las filas de la primera matriz es del mismo orden que las columnas de la segunda matriz.
La matriz H no se puede calcular, ya que las filas de la primera matriz con las columnas de la segunda no son del mismo orden.
[[4250 5100 4990]
 [1675 2010 1955]]

3.
g23: Se produjeron un total de 1955 resistores en la 3era semana
g12: Se produjeron un total de 5100 transitores en la 2da semana

4.
Se utilizaron un total de 5640 resistores durante las 3 semanas.
5640


# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

In [46]:
import numpy as np

R = np.array([[50, 70],[80,110],[60,90]])
# R 3x2 --> iquique/ santiago/ concepcion x routers/switches
C = np.array([[80000],[45000]])
# C = 2x1 --> router/switches x precios

T = R@C
# T = 3 x 1 --> ciudades x precios
print(f"2. La ciudad que tiene más costo de producción fue Santiago con {max(T)}")

C[1] = C[1]*0.9
matriz_nueva = R@C

print(matriz_nueva)

print(f"\n3.\nEl nuevo costo para las ciudades es: \nIquique = ${matriz_nueva[0]}\nSantiago ${matriz_nueva[1]}\nConcepcion ${matriz_nueva[2]}")



2. La ciudad que tiene más costo de producción fue Santiago con [11350000]
[[ 6835000]
 [10855000]
 [ 8445000]]

3.
El nuevo costo para las ciudades es: 
Iquique = $[6835000]
Santiago $[10855000]
Concepcion $[8445000]


# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


In [17]:
import numpy as np

T = np.array([[500, 400, 300, 200, 100],[600, 500, 400, 300, 200],[700,600,500,400,300],[800,700,600,500,400]])
C = np.array([[5, 6, 7, 8, 9, 6],[4, 5, 6, 7, 8, 7],[3, 4, 5, 6, 7, 9],[2, 3, 4, 5, 6, 6],[8, 5, 6, 3, 7, 5]])

G = T@C
print(f"1.\nG:\n{G}")

t14 = G[1-1][4-1]
print(f"t14: en la primera planta se generan mensualmente {t14} productos.")
c53 = C[5-1][3-1]
g35 = G[3-1][5-1]

print(t14, c53, g35)

1.
G:
[[ 6200  7300  8800  9900 11700 10200]
 [ 8400  9600 11600 12800 15400 13500]
 [10600 11900 14400 15700 19100 16800]
 [12800 14200 17200 18600 22800 20100]]
t14: en la primera planta se generan mensualmente 9900 productos.
9900 6 19100


# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

In [48]:
import numpy as np

A = np.array([[3, 1, 2],[1, 2, 1], [4, 1, 3]])

I = np.identity(3)
print(A, I)

[[3 1 2]
 [1 2 1]
 [4 1 3]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

In [ ]:
import numpy as np
#1
print("1.\n")
A = np.array([[2,1],[3,-2]])
#X = np.array([[x],[y]])
B = np.array([[7],[21]])

# X = A_inv * B
A_inv = np.linalg.inv(A)

X = A_inv@B
print(X)

#Comprobar si está bien

B_c = A@X
print(f"\nComprobación:\n{B_c}")

#Comprobar a ver si tengo la misma matriz indentidad

I = A @ A_inv
print(f"\nMatriz identidad: \n{I}")

#Si me da solo 0 o 1 es que está bien.

#2
print("\n2.\n")

A2 = np.array([[1, 1],[0.16,0.2]])
B2 = np.array([[60],[11]]) 

A2_inv = np.linalg.inv(A2)

X2 = A2_inv@B2
print(X2)

#Comprobar identidad

I2 = A2@A2_inv
print(f"Matriz identidad: \n{np.round(I2)}")
print("h = 25\nm = 35")

1.

[[ 5.]
 [-3.]]

Comprobación:
[[ 7.]
 [21.]]

Matriz identidad: 
[[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]

2.

[[25.]
 [35.]]
Matriz identidad: 
[[1. 0.]
 [0. 1.]]
h = 25
m = 35


# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




In [88]:
import numpy as np

#a)
A1 = np.array([[2, 4],[3, 3]])
B1 = np.array([[2900],[3150]])

A1_inv = np.linalg.inv(A1)

X1 = A1_inv @ B1

#PENDIENTE COMPROBAR

B_comp = A1@X1

print(f"\n{B1} \ntendría que ser igual a \n{B_comp}")

print(f"La solución de a: \n{X1}")

#b)
A2 = np.array([[1, 1],[50, 300]])
B2 = np.array([[160],[23000]])

A2_inv = np.linalg.inv(A2)

X2 = A2_inv @ B2

#PENDIENTE COMPROBAR

print(f"\nLa solución de b: \n{X2}")



[[2900]
 [3150]] 
tendría que ser igual a 
[[2900.]
 [3150.]]
La solución de a: 
[[650.]
 [400.]]

La solución de b: 
[[100.]
 [ 60.]]


# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

In [83]:
#1
print("1.\nLa variable x representa las monedas de $10")
print("La variable y representa las monedas de $50")
print("El resultado (variable B) representa lo que tiene la persona.")

#2
print("\n2.\nLa primera ecuación me representa el total de todas las monedas")
print("La segunda ecuación me dice que una persona tiene un total de $8000 entre la suma de monedas de 10 y 50")

#3
import numpy as np

A = np.array([[1, 1], [10, 50]])
B = np.array([[200],[8000]])

A_inv = np.linalg.inv(A)

X = A_inv @ B

print(X)
print(f"\n3. Hay {X[0,0]} monedas de $10 y {X[1,0]} monedas de $50")

1.
La variable x representa las monedas de $10
La variable y representa las monedas de $50
El resultado (variable B) representa lo que tiene la persona.

2.
La primera ecuación me representa el total de todas las monedas
La segunda ecuación me dice que una persona tiene un total de $8000 entre la suma de monedas de 10 y 50
[[ 50.]
 [150.]]

3. Hay 50.0 monedas de $10 y 150.0 monedas de $50


# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

In [11]:
#1
# la "p" representa patos
# la "v" representa vacas
# 132 representa el total de animales

#2p + 4v = 402 --> cada pato tiene 2 patas y las vacas tienen 4 patas = entre los dos animales hay un total de 402 patas

#2
import numpy as np
A = np.array([[1,1],[2,4]])
B = np.array([[132],[402]])

A_inv = np.linalg.inv(A)

X = A_inv@B

#Comprobar
B_comprobar = A@X
print(f"Comprobar:\n{B} \ntiene que ser igual a \n{B_comprobar}")

print(f"\n2.\nHay un total de {X[0,0]} patos y un total de {X[1,0]} vacas.")


Comprobar:
[[132]
 [402]] 
tiene que ser igual a 
[[132.]
 [402.]]

2.
Hay un total de 63.0 patos y un total de 69.0 vacas.


# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.

In [ ]:
#1
print("1. \n'x' representa el precio de los cables USB e 'y' representa el precio de los pendrives")
print("5,6 y 3,7 representan la cantidad de productos.")
print("82890 y 59900 representan el total,")

#2
import numpy as np

A = np.array([[5,6],[3,7]])
B = np.array([[82890],[59900]])

A_inv = np.linalg.inv(A)

X = A_inv@B

#Comprobar
B_comprobar = A@X
print(f"\nComprobar \n{B} \ntiene que ser igual a \n{B_comprobar}")

print(f"\n2. Cada cable USB vale ${round(X[0,0])} y cada pendrive vale ${round(X[1,0])}. Por lo tanto Luis y Pablo pagaron ${round(X[0,0])} por cada cable USB.")


1. 
'x' representa el precio de los cables USB e 'y' representa el precio de los pendrives
5,6 y 3,7 representan la cantidad de productos.
82890 y 59900 representan el total,

Comprobar 
[[82890]
 [59900]] 
tiene que ser igual a 
[[82890.]
 [59900.]]

2. Cada cable USB vale $12990 y cada pendrive vale $2990. Por lo tanto Luis y pablo pagaron $12990 por cada cable USB.
